channels:
- conda-forge
dependencies:
- python=3.11.7
- pip<=24.0
- pip:
  - mlflow==2.12.2
  - accelerate==0.30.0
  - astunparse==1.6.3
  - cloudpickle==3.0.0
  - google-auth==2.27.0
  - numpy==1.26.4
  - optree==0.11.0
  - packaging==23.2
  - pandas==2.2.2
  - protobuf==4.23.4
  - pydantic==2.6.1
  - pyyaml==6.0.1
  - requests==2.31.0
  - torch==2.2.1
  - transformers==4.39.3
  - Flask==3.0.3
name: mlflow-env
